# Generated by Django 4.0.3 on 2022-04-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('start_data', models.DateTimeField(null=True, unique=True)),
                ('end_data', models.DateTimeField(null=True, unique=True)),
                ('allday', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_user', models.CharField(blank=True, max_length=100, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_user', models.CharField(blank=True, max_length=100, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDX', models.CharField(blank=True, max_length=100, null=True)),
                ('ORDER_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('MALL_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('ORDER_STATUS', models.CharField(max_length=100)),
                ('scm_status', models.CharField(blank=True, max_length=100, null=True)),
                ('PAY_COST', models.IntegerField()),
                ('ORDER_DATE', models.DateTimeField(blank=True, null=True)),
                ('MALL_PRODUCT_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('PRODUCT_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('SKU_VALUE', models.CharField(blank=True, max_length=100, null=True)),
                ('DELIVERY_METHOD_STR', models.CharField(blank=True, max_length=100, null=True)),
                ('DELV_COST', models.IntegerField(blank=True, null=True)),
                ('P_EA', models.IntegerField(blank=True, null=True)),
                ('REG_DATE', models.DateTimeField(blank=True, null=True)),
                ('ORD_CONFIRM_DATE', models.DateTimeField(blank=True, null=True)),
                ('RTN_DT', models.DateTimeField(blank=True, null=True)),
                ('CHNG_DT', models.DateTimeField(blank=True, null=True)),
                ('DELIVERY_CONFIRM_DATE', models.DateTimeField(blank=True, null=True)),
                ('CANCEL_DT', models.DateTimeField(blank=True, null=True)),
                ('DELIVERY_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('INVOICE_NO', models.BigIntegerField(blank=True, null=True)),
                ('INV_SEND_MSG', models.CharField(blank=True, max_length=100, null=True)),
                ('INV_SEND_DM', models.DateTimeField(blank=True, null=True)),
                ('USER_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('USER_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('USER_TEL', models.CharField(blank=True, max_length=100, null=True)),
                ('USER_CEL', models.CharField(blank=True, max_length=100, null=True)),
                ('RECEIVE_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('RECEIVE_TEL', models.CharField(blank=True, max_length=100, null=True)),
                ('RECEIVE_CEL', models.CharField(blank=True, max_length=100, null=True)),
                ('RECEIVE_ZIPCODE', models.CharField(blank=True, max_length=10, null=True)),
                ('RECEIVE_ADDR', models.CharField(blank=True, max_length=100, null=True)),
                ('DELV_MSG', models.CharField(blank=True, max_length=100, null=True)),
                ('HOPE_DELV_DATE', models.CharField(blank=True, max_length=10, null=True)),
                ('memo', models.CharField(blank=True, max_length=10, null=True)),
                ('item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_quan', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_user', models.CharField(blank=True, max_length=100, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checker', models.CharField(blank=True, max_length=100, null=True)),
                ('check_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.ManyToManyField(related_name='order', to='B2C.order_list')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_user', models.CharField(blank=True, max_length=100, null=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('sumpacking', models.BooleanField()),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=models.SET('해당 카테고리는 삭제 되었습니다.'), related_name='category', to='B2C.category')),
                ('packing', models.ForeignKey(on_delete=models.SET('해당 포장상태가 삭제되었습니다.'), related_name='boxing', to='B2C.packing')),
                ('pdfactory', models.ForeignKey(on_delete=models.SET('해당 공장이 삭제되었습니다.'), related_name='pdfactory', to='B2C.factory')),
                ('smfactory', models.ForeignKey(on_delete=models.SET('해당 공장이 삭제되었습니다.'), related_name='smfactory', to='B2C.factory')),
            ],
        ),
    ]
